version: '3.8'

networks:
  internal:

services:
  gateway:
    build: ./gateway
    ports:
      - "5000:80"
    networks:
      - internal
    container_name: gateway

  service1:
    build: ./services/service1
    networks:
      - internal
    container_name: service1

  service2:
    build: ./services/service2
    networks:
      - internal
    container_name: service2

  service3:
    build: ./services/service3
    networks:
      - internal
    container_name: service3
