version: '3.8'

services:
  service1:
    build: ./services/service1
    container_name: service1

  service2:
    build: ./services/service2
    container_name: service2
    ports:
      - "5000:5002"
    depends_on:
      - service1
