---
# ================
# GATEWAY SERVICE
# ================

apiVersion: v1
kind: Service
metadata:
  name: frontend-gateway
  namespace: app-ns
  labels:
    app: orderApp
    component: gateway

spec:
  type: NodePort
  selector: 
    app: orderApp
    component: gateway
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: http

---
# ================
# POSTGRESQL
# ================

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: app-ns
  labels:
    app: orderApp
    component: ps-db
spec:
  type: ClusterIP
  selector:
    app: orderApp
    component: ps-db
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres

---
# ================
# REDIS
# ================

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: app-ns
  labels:
    app: orderApp
    component: redis
spec:
  type: ClusterIP
  selector:
    app: orderApp
    component: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis

---
# ================
# AUTH SERVICE
# ================

apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: app-ns
  labels:
    app: orderApp
    component: auth

spec:
  type: ClusterIP
  selector:
    app: orderApp
    component: auth
  ports:
  - port: 5001
    targetPort: 5001
    name: http
