events {
	worker_connections 1024;
}

http {
	server {
		listen 80;

		location /api/service1/ {
			proxy_pass http://service1:5001/;
		}

		location /api/service2/ {
			proxy_pass http://service2:5002/;
		}
	}
}
