server {
	listen 80;
	server_name localhost;
	
	location / {
		root /usr/share/nginx/html;
		try_files $uri $uri/ /index.html;
	}

	location /api/auth/ {
		proxy_pass http://auth:5001/;
		proxy_set_header Host $host;
	}

	location /api/users/ {
		proxy_pass http://users:5002/;
		proxy_set_header Host $host;
	}

	location /api/orders/ {
		proxy_pass http://orders:5003/;
		proxy_set_header Host $host;
	}
}
